/* eslint-disable */
import * as Types from '@graphcommerce/graphql-mesh/.mesh';

export type ProductPageMeta_BundleProduct_Fragment = { __typename: 'BundleProduct', sku?: string | null, name?: string | null, url_key?: string | null, meta_title?: string | null, meta_description?: string | null, uid: string, url_rewrites?: Array<{ url?: string | null } | null> | null, price_range: { minimum_price: { final_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } }, media_gallery?: Array<{ url?: string | null } | { url?: string | null } | null> | null, categories?: Array<{ uid: string, name?: string | null } | null> | null };

export type ProductPageMeta_ConfigurableProduct_Fragment = { __typename: 'ConfigurableProduct', sku?: string | null, name?: string | null, url_key?: string | null, meta_title?: string | null, meta_description?: string | null, uid: string, url_rewrites?: Array<{ url?: string | null } | null> | null, price_range: { minimum_price: { final_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } }, media_gallery?: Array<{ url?: string | null } | { url?: string | null } | null> | null, categories?: Array<{ uid: string, name?: string | null } | null> | null };

export type ProductPageMeta_DownloadableProduct_Fragment = { __typename: 'DownloadableProduct', sku?: string | null, name?: string | null, url_key?: string | null, meta_title?: string | null, meta_description?: string | null, uid: string, url_rewrites?: Array<{ url?: string | null } | null> | null, price_range: { minimum_price: { final_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } }, media_gallery?: Array<{ url?: string | null } | { url?: string | null } | null> | null, categories?: Array<{ uid: string, name?: string | null } | null> | null };

export type ProductPageMeta_GroupedProduct_Fragment = { __typename: 'GroupedProduct', sku?: string | null, name?: string | null, url_key?: string | null, meta_title?: string | null, meta_description?: string | null, uid: string, url_rewrites?: Array<{ url?: string | null } | null> | null, price_range: { minimum_price: { final_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } }, media_gallery?: Array<{ url?: string | null } | { url?: string | null } | null> | null, categories?: Array<{ uid: string, name?: string | null } | null> | null };

export type ProductPageMeta_SimpleProduct_Fragment = { __typename: 'SimpleProduct', sku?: string | null, name?: string | null, url_key?: string | null, meta_title?: string | null, meta_description?: string | null, uid: string, url_rewrites?: Array<{ url?: string | null } | null> | null, price_range: { minimum_price: { final_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } }, media_gallery?: Array<{ url?: string | null } | { url?: string | null } | null> | null, categories?: Array<{ uid: string, name?: string | null } | null> | null };

export type ProductPageMeta_VirtualProduct_Fragment = { __typename: 'VirtualProduct', sku?: string | null, name?: string | null, url_key?: string | null, meta_title?: string | null, meta_description?: string | null, uid: string, url_rewrites?: Array<{ url?: string | null } | null> | null, price_range: { minimum_price: { final_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } }, media_gallery?: Array<{ url?: string | null } | { url?: string | null } | null> | null, categories?: Array<{ uid: string, name?: string | null } | null> | null };

export type ProductPageMetaFragment = ProductPageMeta_BundleProduct_Fragment | ProductPageMeta_ConfigurableProduct_Fragment | ProductPageMeta_DownloadableProduct_Fragment | ProductPageMeta_GroupedProduct_Fragment | ProductPageMeta_SimpleProduct_Fragment | ProductPageMeta_VirtualProduct_Fragment;
