/* hash:475616464 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/magento-cart-items/hooks/useRemoveItemFromCart */

import { useRemoveItemFromCart as useRemoveItemFromCartGoogleDatalayerRemoveItemFromCart } from '@graphcommerce/google-datalayer/plugins/GoogleDatalayerRemoveItemFromCart'
/** @see {@link file://./useRemoveItemFromCart.ts} for source of original */
/** SOURCE_START */
import { useFormGqlMutationCart } from '@graphcommerce/magento-cart/hooks'
import type { UseFormGraphQlOptions } from '@graphcommerce/react-hook-form'
import type { DistributedOmit } from 'type-fest'
import type { CartItemFragment } from '../Api/CartItem.gql'
import type {
  RemoveItemFromCartMutation,
  RemoveItemFromCartMutationVariables,
} from '../components/RemoveItemFromCart/RemoveItemFromCart.gql'
import { RemoveItemFromCartDocument } from '../components/RemoveItemFromCart/RemoveItemFromCart.gql'

export type UseRemoveItemFromCartProps = DistributedOmit<CartItemFragment, '__typename'> &
  Omit<
    UseFormGraphQlOptions<RemoveItemFromCartMutation, RemoveItemFromCartMutationVariables>,
    'errors'
  >
export function useRemoveItemFromCartOriginal(props: UseRemoveItemFromCartProps) {
  const { uid, errors, ...options } = props
  const form = useFormGqlMutationCart(RemoveItemFromCartDocument, {
    defaultValues: {
      uid,
    },
    ...options,
  })
  const { handleSubmit } = form
  const submit = handleSubmit(() => {})
  return {
    ...form,
    submit,
  }
}

/** SOURCE_END */

const logged: Set<string> = new Set()
const logOnce = (log: string, ...additional: unknown[]) => {
  if (logged.has(log)) return
  logged.add(log)
  console.warn(log, ...additional)
}

const useRemoveItemFromCartGoogleDatalayerRemoveItemFromCartInterceptor: typeof useRemoveItemFromCartOriginal =
  (...args) => {
    return useRemoveItemFromCartGoogleDatalayerRemoveItemFromCart(
      useRemoveItemFromCartOriginal,
      ...args,
    )
  }

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./useRemoveItemFromCart.ts} for original source file
 * @see {useRemoveItemFromCartGoogleDatalayerRemoveItemFromCart} for source of applied plugin
 */
export const useRemoveItemFromCart =
  useRemoveItemFromCartGoogleDatalayerRemoveItemFromCartInterceptor
