/* hash:685387758 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/magento-cart-items/components/UpdateItemQuantity/UpdateItemQuantity */

/** @see {@link file://./UpdateItemQuantity.tsx} for source of original */
/** SOURCE_START */
import type { NumberFieldElementProps } from '@graphcommerce/ecommerce-ui'
import { NumberFieldElement } from '@graphcommerce/ecommerce-ui'
import { UpdateItemQuantity as UpdateItemQuantityGoogleDatalayerUseRemoveItemFromCart } from '@graphcommerce/google-datalayer/plugins/GoogleDatalayerUseRemoveItemFromCart'
import { ApolloCartErrorSnackbar, useFormGqlMutationCart } from '@graphcommerce/magento-cart'
import type { UseFormGraphQlOptions } from '@graphcommerce/react-hook-form'
import { FormAutoSubmit } from '@graphcommerce/react-hook-form'
import type { SxProps, Theme } from '@mui/material'
import React from 'react'
import type { DistributedOmit as OmitPrev } from 'type-fest'
import type {
  UpdateItemQuantityMutation,
  UpdateItemQuantityMutationVariables,
} from './UpdateItemQuantity.gql'
import { UpdateItemQuantityDocument } from './UpdateItemQuantity.gql'

type UpdateItemQuantityFormReturn = UseFormGraphQlOptions<
  UpdateItemQuantityMutation,
  UpdateItemQuantityMutationVariables
>
export type UpdateItemQuantityProps = Omit<UpdateItemQuantityMutationVariables, 'cartId'> & {
  formOptions?: Omit<UpdateItemQuantityFormReturn, 'mode' | 'defaultValues'>
  textInputProps?: Omit<
    NumberFieldElementProps<UpdateItemQuantityMutationVariables>,
    'rules' | 'shouldUnregister' | 'defaultValue' | 'control' | 'disabled'
  >
  sx?: SxProps<Theme>
}
export function UpdateItemQuantityOriginal(props: UpdateItemQuantityProps) {
  const { uid, quantity, sx, textInputProps, formOptions } = props
  const form = useFormGqlMutationCart(UpdateItemQuantityDocument, {
    defaultValues: {
      uid,
      quantity,
    },
    mode: 'onChange',
    ...formOptions,
  })
  const { handleSubmit, formState, error, reset, control } = form
  const submit = handleSubmit(() => {})
  return (
    <form noValidate onSubmit={submit}>
      <FormAutoSubmit control={control} submit={submit} leading />
      <NumberFieldElement
        control={control}
        name='quantity'
        size='small'
        variant='standard'
        inputProps={{
          min: 1,
        }}
        InputProps={{
          disableUnderline: true,
        }}
        error={!!formState.errors.quantity}
        helperText={formState.errors.quantity?.message}
        sx={sx}
        {...textInputProps}
      />
      <ApolloCartErrorSnackbar
        error={error}
        onClose={() =>
          reset({
            quantity,
          })
        }
      />
    </form>
  )
}

/** SOURCE_END */

type UpdateItemQuantityGoogleDatalayerUseRemoveItemFromCartProps = OmitPrev<
  React.ComponentProps<typeof UpdateItemQuantityGoogleDatalayerUseRemoveItemFromCart>,
  'Prev'
>

const UpdateItemQuantityGoogleDatalayerUseRemoveItemFromCartInterceptor = (
  props: UpdateItemQuantityGoogleDatalayerUseRemoveItemFromCartProps,
) => (
  <UpdateItemQuantityGoogleDatalayerUseRemoveItemFromCart
    {...props}
    Prev={UpdateItemQuantityOriginal}
  />
)

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./UpdateItemQuantity.tsx} for original source file
 * @see {UpdateItemQuantityGoogleDatalayerUseRemoveItemFromCart} for source of applied plugin
 */
export const UpdateItemQuantity = UpdateItemQuantityGoogleDatalayerUseRemoveItemFromCartInterceptor
