/* eslint-disable */
import * as Types from '@graphcommerce/graphql-mesh/.mesh';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

export const OrderCardItemImagesDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"OrderCardItemImages"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"urlKeys"}},"type":{"kind":"NonNullType","type":{"kind":"ListType","type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"products"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"filter"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"url_key"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"in"},"value":{"kind":"Variable","name":{"kind":"Name","value":"urlKeys"}}}]}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"items"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"thumbnail"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"label"}},{"kind":"Field","name":{"kind":"Name","value":"disabled"}}]}},{"kind":"Field","name":{"kind":"Name","value":"url_key"}}]}}]}}]}}]} as unknown as DocumentNode<OrderCardItemImagesQuery, OrderCardItemImagesQueryVariables>;
export type OrderCardItemImagesQueryVariables = Types.Exact<{
  urlKeys: Array<Types.Scalars['String']['input']>;
}>;


export type OrderCardItemImagesQuery = { products?: { items?: Array<{ uid: string, url_key?: string | null, thumbnail?: { url?: string | null, label?: string | null, disabled?: boolean | null } | null } | { uid: string, url_key?: string | null, thumbnail?: { url?: string | null, label?: string | null, disabled?: boolean | null } | null } | { uid: string, url_key?: string | null, thumbnail?: { url?: string | null, label?: string | null, disabled?: boolean | null } | null } | { uid: string, url_key?: string | null, thumbnail?: { url?: string | null, label?: string | null, disabled?: boolean | null } | null } | { uid: string, url_key?: string | null, thumbnail?: { url?: string | null, label?: string | null, disabled?: boolean | null } | null } | { uid: string, url_key?: string | null, thumbnail?: { url?: string | null, label?: string | null, disabled?: boolean | null } | null } | null> | null } | null };
