/* hash:160576274 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/magento-cart/components/CartStartCheckout/CartStartCheckoutLinkOrButton */
import { CartStartCheckoutLinkOrButton as CartStartCheckoutLinkOrButtonGoogleDatalayerCartStartCheckoutLinkOrButton } from '@graphcommerce/google-datalayer/plugins/GoogleDatalayerCartStartCheckoutLinkOrButton'
/** @see {@link file://./CartStartCheckoutLinkOrButton.tsx} for source of original */
/** SOURCE_START */
import type { LinkOrButtonProps } from '@graphcommerce/next-ui'
import { iconChevronRight, IconSvg, LinkOrButton } from '@graphcommerce/next-ui'
import { Trans } from '@lingui/react'
import type { SxProps, Theme } from '@mui/material'
import React from 'react'
import type { DistributedOmit as OmitPrev } from 'type-fest'
import { useCheckoutShouldLoginToContinue } from '../../hooks'
import type { CartStartCheckoutFragment } from './CartStartCheckout.gql'

export type CartStartCheckoutLinkOrButtonProps = {
  children?: React.ReactNode
  sx?: SxProps<Theme>
  disabled?: boolean
  cart?: CartStartCheckoutFragment | null | undefined
  onStart?: (
    e: React.MouseEvent<HTMLButtonElement & HTMLAnchorElement & HTMLSpanElement>,
    cart: CartStartCheckoutFragment | null | undefined,
  ) => void
  linkOrButtonProps?: LinkOrButtonProps
}
export function CartStartCheckoutLinkOrButtonOriginal(props: CartStartCheckoutLinkOrButtonProps) {
  const {
    onStart,
    disabled,
    linkOrButtonProps: { onClick, button, ...linkOrButtonProps } = {},
    cart,
  } = props
  const shouldLoginToContinue = useCheckoutShouldLoginToContinue()
  const hasTotals = (cart?.prices?.grand_total?.value ?? 0) > 0
  const hasErrors = cart?.items?.some((item) => (item?.errors?.length ?? 0) > 0)
  return (
    <LinkOrButton
      href='/checkout'
      onClick={(
        e: React.MouseEvent<HTMLButtonElement & HTMLAnchorElement & HTMLSpanElement, MouseEvent>,
      ) => {
        onClick?.(e)
        onStart?.(e, cart)
      }}
      button={{
        variant: 'pill',
        ...button,
      }}
      disabled={disabled || !hasTotals || hasErrors || shouldLoginToContinue}
      color='secondary'
      endIcon={<IconSvg src={iconChevronRight} />}
      {...linkOrButtonProps}
    >
      <Trans id='Next' />
    </LinkOrButton>
  )
}

/** SOURCE_END */

type CartStartCheckoutLinkOrButtonGoogleDatalayerCartStartCheckoutLinkOrButtonProps = OmitPrev<
  React.ComponentProps<
    typeof CartStartCheckoutLinkOrButtonGoogleDatalayerCartStartCheckoutLinkOrButton
  >,
  'Prev'
>

const CartStartCheckoutLinkOrButtonGoogleDatalayerCartStartCheckoutLinkOrButtonInterceptor = (
  props: CartStartCheckoutLinkOrButtonGoogleDatalayerCartStartCheckoutLinkOrButtonProps,
) => (
  <CartStartCheckoutLinkOrButtonGoogleDatalayerCartStartCheckoutLinkOrButton
    {...props}
    Prev={CartStartCheckoutLinkOrButtonOriginal}
  />
)

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./CartStartCheckoutLinkOrButton.tsx} for original source file
 * @see {CartStartCheckoutLinkOrButtonGoogleDatalayerCartStartCheckoutLinkOrButton} for source of applied plugin
 */
export const CartStartCheckoutLinkOrButton =
  CartStartCheckoutLinkOrButtonGoogleDatalayerCartStartCheckoutLinkOrButtonInterceptor
