/* eslint-disable */
import * as Types from '@graphcommerce/graphql-mesh/.mesh';

export type Product_ViewItem_BundleProduct_Fragment = { __typename: 'BundleProduct', uid: string, name?: string | null, sku?: string | null, url_key?: string | null, price_range: { minimum_price: { regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, discount?: { amount_off?: number | null, percent_off?: number | null } | null, final_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } }, categories?: Array<{ uid: string, name?: string | null, url_path?: string | null, include_in_menu?: number | null, breadcrumbs?: Array<{ category_name?: string | null, category_uid: string, category_url_path?: string | null, category_level?: number | null } | null> | null } | null> | null };

export type Product_ViewItem_ConfigurableProduct_Fragment = { __typename: 'ConfigurableProduct', uid: string, name?: string | null, sku?: string | null, url_key?: string | null, price_range: { minimum_price: { regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, discount?: { amount_off?: number | null, percent_off?: number | null } | null, final_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } }, categories?: Array<{ uid: string, name?: string | null, url_path?: string | null, include_in_menu?: number | null, breadcrumbs?: Array<{ category_name?: string | null, category_uid: string, category_url_path?: string | null, category_level?: number | null } | null> | null } | null> | null };

export type Product_ViewItem_DownloadableProduct_Fragment = { __typename: 'DownloadableProduct', uid: string, name?: string | null, sku?: string | null, url_key?: string | null, price_range: { minimum_price: { regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, discount?: { amount_off?: number | null, percent_off?: number | null } | null, final_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } }, categories?: Array<{ uid: string, name?: string | null, url_path?: string | null, include_in_menu?: number | null, breadcrumbs?: Array<{ category_name?: string | null, category_uid: string, category_url_path?: string | null, category_level?: number | null } | null> | null } | null> | null };

export type Product_ViewItem_GroupedProduct_Fragment = { __typename: 'GroupedProduct', uid: string, name?: string | null, sku?: string | null, url_key?: string | null, price_range: { minimum_price: { regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, discount?: { amount_off?: number | null, percent_off?: number | null } | null, final_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } }, categories?: Array<{ uid: string, name?: string | null, url_path?: string | null, include_in_menu?: number | null, breadcrumbs?: Array<{ category_name?: string | null, category_uid: string, category_url_path?: string | null, category_level?: number | null } | null> | null } | null> | null };

export type Product_ViewItem_SimpleProduct_Fragment = { __typename: 'SimpleProduct', uid: string, name?: string | null, sku?: string | null, url_key?: string | null, price_range: { minimum_price: { regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, discount?: { amount_off?: number | null, percent_off?: number | null } | null, final_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } }, categories?: Array<{ uid: string, name?: string | null, url_path?: string | null, include_in_menu?: number | null, breadcrumbs?: Array<{ category_name?: string | null, category_uid: string, category_url_path?: string | null, category_level?: number | null } | null> | null } | null> | null };

export type Product_ViewItem_VirtualProduct_Fragment = { __typename: 'VirtualProduct', uid: string, name?: string | null, sku?: string | null, url_key?: string | null, price_range: { minimum_price: { regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, discount?: { amount_off?: number | null, percent_off?: number | null } | null, final_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } }, categories?: Array<{ uid: string, name?: string | null, url_path?: string | null, include_in_menu?: number | null, breadcrumbs?: Array<{ category_name?: string | null, category_uid: string, category_url_path?: string | null, category_level?: number | null } | null> | null } | null> | null };

export type Product_ViewItemFragment = Product_ViewItem_BundleProduct_Fragment | Product_ViewItem_ConfigurableProduct_Fragment | Product_ViewItem_DownloadableProduct_Fragment | Product_ViewItem_GroupedProduct_Fragment | Product_ViewItem_SimpleProduct_Fragment | Product_ViewItem_VirtualProduct_Fragment;
