/* eslint-disable */
import * as Types from '@graphcommerce/graphql-mesh/.mesh';

export type JsonLdProduct_BundleProduct_Fragment = { uid: string, name?: string | null, sku?: string | null, url_key?: string | null, description?: { html: string } | null, media_gallery?: Array<{ __typename: 'ProductImage', url?: string | null, label?: string | null } | { __typename: 'ProductVideo', label?: string | null } | null> | null, categories?: Array<{ uid: string, url_key?: string | null, name?: string | null } | null> | null, price_range: { minimum_price: { regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, final_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } } };

export type JsonLdProduct_ConfigurableProduct_Fragment = { uid: string, name?: string | null, sku?: string | null, url_key?: string | null, description?: { html: string } | null, media_gallery?: Array<{ __typename: 'ProductImage', url?: string | null, label?: string | null } | { __typename: 'ProductVideo', label?: string | null } | null> | null, categories?: Array<{ uid: string, url_key?: string | null, name?: string | null } | null> | null, price_range: { minimum_price: { regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, final_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } } };

export type JsonLdProduct_DownloadableProduct_Fragment = { uid: string, name?: string | null, sku?: string | null, url_key?: string | null, description?: { html: string } | null, media_gallery?: Array<{ __typename: 'ProductImage', url?: string | null, label?: string | null } | { __typename: 'ProductVideo', label?: string | null } | null> | null, categories?: Array<{ uid: string, url_key?: string | null, name?: string | null } | null> | null, price_range: { minimum_price: { regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, final_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } } };

export type JsonLdProduct_GroupedProduct_Fragment = { uid: string, name?: string | null, sku?: string | null, url_key?: string | null, description?: { html: string } | null, media_gallery?: Array<{ __typename: 'ProductImage', url?: string | null, label?: string | null } | { __typename: 'ProductVideo', label?: string | null } | null> | null, categories?: Array<{ uid: string, url_key?: string | null, name?: string | null } | null> | null, price_range: { minimum_price: { regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, final_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } } };

export type JsonLdProduct_SimpleProduct_Fragment = { uid: string, name?: string | null, sku?: string | null, url_key?: string | null, description?: { html: string } | null, media_gallery?: Array<{ __typename: 'ProductImage', url?: string | null, label?: string | null } | { __typename: 'ProductVideo', label?: string | null } | null> | null, categories?: Array<{ uid: string, url_key?: string | null, name?: string | null } | null> | null, price_range: { minimum_price: { regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, final_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } } };

export type JsonLdProduct_VirtualProduct_Fragment = { uid: string, name?: string | null, sku?: string | null, url_key?: string | null, description?: { html: string } | null, media_gallery?: Array<{ __typename: 'ProductImage', url?: string | null, label?: string | null } | { __typename: 'ProductVideo', label?: string | null } | null> | null, categories?: Array<{ uid: string, url_key?: string | null, name?: string | null } | null> | null, price_range: { minimum_price: { regular_price: { currency?: Types.CurrencyEnum | null, value?: number | null }, final_price: { currency?: Types.CurrencyEnum | null, value?: number | null } } } };

export type JsonLdProductFragment = JsonLdProduct_BundleProduct_Fragment | JsonLdProduct_ConfigurableProduct_Fragment | JsonLdProduct_DownloadableProduct_Fragment | JsonLdProduct_GroupedProduct_Fragment | JsonLdProduct_SimpleProduct_Fragment | JsonLdProduct_VirtualProduct_Fragment;
