/* eslint-disable */
import * as Types from '@graphcommerce/graphql-mesh/.mesh';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

export const AccountDashboardReviewsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"AccountDashboardReviews"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"customer"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"reviews"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"items"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"average_rating"}},{"kind":"Field","name":{"kind":"Name","value":"created_at"}},{"kind":"Field","name":{"kind":"Name","value":"product"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"url_key"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"thumbnail"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"label"}},{"kind":"Field","name":{"kind":"Name","value":"disabled"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"nickname"}},{"kind":"Field","name":{"kind":"Name","value":"summary"}},{"kind":"Field","name":{"kind":"Name","value":"text"}},{"kind":"Field","name":{"kind":"Name","value":"ratings_breakdown"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"value"}}]}}]}}]}}]}}]}}]} as unknown as DocumentNode<AccountDashboardReviewsQuery, AccountDashboardReviewsQueryVariables>;
export type AccountDashboardReviewsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type AccountDashboardReviewsQuery = { customer?: { reviews: { items: Array<{ average_rating: number, created_at: string, nickname: string, summary: string, text: string, product: { uid: string, url_key?: string | null, name?: string | null, thumbnail?: { url?: string | null, label?: string | null, disabled?: boolean | null } | null } | { uid: string, url_key?: string | null, name?: string | null, thumbnail?: { url?: string | null, label?: string | null, disabled?: boolean | null } | null } | { uid: string, url_key?: string | null, name?: string | null, thumbnail?: { url?: string | null, label?: string | null, disabled?: boolean | null } | null } | { uid: string, url_key?: string | null, name?: string | null, thumbnail?: { url?: string | null, label?: string | null, disabled?: boolean | null } | null } | { uid: string, url_key?: string | null, name?: string | null, thumbnail?: { url?: string | null, label?: string | null, disabled?: boolean | null } | null } | { uid: string, url_key?: string | null, name?: string | null, thumbnail?: { url?: string | null, label?: string | null, disabled?: boolean | null } | null }, ratings_breakdown: Array<{ name: string, value: string } | null> } | null> } } | null };
