/* hash:1598665784 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/ecommerce-ui/components/PreviewMode/previewModeDefaults */

/** @see {@link file://./previewModeDefaults.ts} for source of original */
/** SOURCE_START */
import type { PreviewData } from '@graphcommerce/graphql'
import { previewModeDefaults as previewModeDefaultshygraphPreviewModeDefaults } from '@graphcommerce/hygraph-ui/plugins/hygraphPreviewModeDefaults'

export function previewModeDefaultsOriginal(): PreviewData {
  return {}
}

/** SOURCE_END */

const logged: Set<string> = new Set()
const logOnce = (log: string, ...additional: unknown[]) => {
  if (logged.has(log)) return
  logged.add(log)
  console.warn(log, ...additional)
}

const previewModeDefaultshygraphPreviewModeDefaultsInterceptor: typeof previewModeDefaultsOriginal =
  (...args) => {
    return previewModeDefaultshygraphPreviewModeDefaults(previewModeDefaultsOriginal, ...args)
  }

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./previewModeDefaults.ts} for original source file
 * @see {previewModeDefaultshygraphPreviewModeDefaults} for source of applied plugin
 */
export const previewModeDefaults = previewModeDefaultshygraphPreviewModeDefaultsInterceptor
