/* hash:1100066509 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/ecommerce-ui/components/PreviewMode/PreviewModeToolbar */
import { PreviewModeToolbar as PreviewModeToolbarHygraphPreviewModeToolbar } from '@graphcommerce/hygraph-ui/plugins/HygraphPreviewModeToolbar'
import type { DistributedOmit as OmitPrev } from 'type-fest'

/** @see {@link file://./PreviewModeToolbar.tsx} for source of original */
/** SOURCE_START */
export type PreviewModeToolbarProps = Record<string, unknown>
export function PreviewModeToolbarOriginal(props: PreviewModeToolbarProps) {
  return null
}

/** SOURCE_END */

type PreviewModeToolbarHygraphPreviewModeToolbarProps = OmitPrev<
  React.ComponentProps<typeof PreviewModeToolbarHygraphPreviewModeToolbar>,
  'Prev'
>

const PreviewModeToolbarHygraphPreviewModeToolbarInterceptor = (
  props: PreviewModeToolbarHygraphPreviewModeToolbarProps,
) => <PreviewModeToolbarHygraphPreviewModeToolbar {...props} Prev={PreviewModeToolbarOriginal} />

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./PreviewModeToolbar.tsx} for original source file
 * @see {PreviewModeToolbarHygraphPreviewModeToolbar} for source of applied plugin
 */
export const PreviewModeToolbar = PreviewModeToolbarHygraphPreviewModeToolbarInterceptor
