/* eslint-disable */
import * as Types from '@graphcommerce/graphql-mesh/.mesh';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

export const HandleRedirectDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"HandleRedirect"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"url"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"route"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"url"},"value":{"kind":"Variable","name":{"kind":"Name","value":"url"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"}},{"kind":"Field","name":{"kind":"Name","value":"redirect_code"}},{"kind":"Field","name":{"kind":"Name","value":"relative_url"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"InlineFragment","typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"ProductInterface"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"url_key"}}]}},{"kind":"InlineFragment","typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CategoryInterface"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"url_key"}}]}},{"kind":"InlineFragment","typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CmsPage"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url_key"}},{"kind":"Field","name":{"kind":"Name","value":"identifier"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"products"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"filter"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"url_key"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"eq"},"value":{"kind":"Variable","name":{"kind":"Name","value":"url"}}}]}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"items"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"url_key"}}]}}]}}]}}]} as unknown as DocumentNode<HandleRedirectQuery, HandleRedirectQueryVariables>;
export type HandleRedirectQueryVariables = Types.Exact<{
  url: Types.Scalars['String']['input'];
}>;


export type HandleRedirectQuery = { route?: { __typename: 'BundleProduct', uid: string, url_key?: string | null, redirect_code: number, relative_url?: string | null, type?: Types.UrlRewriteEntityTypeEnum | null } | { __typename: 'CategoryTree', uid: string, url_key?: string | null, redirect_code: number, relative_url?: string | null, type?: Types.UrlRewriteEntityTypeEnum | null } | { __typename: 'CmsPage', url_key?: string | null, identifier?: string | null, redirect_code: number, relative_url?: string | null, type?: Types.UrlRewriteEntityTypeEnum | null } | { __typename: 'ConfigurableProduct', uid: string, url_key?: string | null, redirect_code: number, relative_url?: string | null, type?: Types.UrlRewriteEntityTypeEnum | null } | { __typename: 'DownloadableProduct', uid: string, url_key?: string | null, redirect_code: number, relative_url?: string | null, type?: Types.UrlRewriteEntityTypeEnum | null } | { __typename: 'GroupedProduct', uid: string, url_key?: string | null, redirect_code: number, relative_url?: string | null, type?: Types.UrlRewriteEntityTypeEnum | null } | { __typename: 'RoutableUrl', redirect_code: number, relative_url?: string | null, type?: Types.UrlRewriteEntityTypeEnum | null } | { __typename: 'SimpleProduct', uid: string, url_key?: string | null, redirect_code: number, relative_url?: string | null, type?: Types.UrlRewriteEntityTypeEnum | null } | { __typename: 'VirtualProduct', uid: string, url_key?: string | null, redirect_code: number, relative_url?: string | null, type?: Types.UrlRewriteEntityTypeEnum | null } | null, products?: { items?: Array<{ uid: string, url_key?: string | null } | { uid: string, url_key?: string | null } | { uid: string, url_key?: string | null } | { uid: string, url_key?: string | null } | { uid: string, url_key?: string | null } | { uid: string, url_key?: string | null } | null> | null } | null };
