/* eslint-disable */
import * as Types from '@graphcommerce/graphql-mesh/.mesh';

export type ProductPageGallery_BundleProduct_Fragment = { url_key?: string | null, media_gallery?: Array<{ __typename: 'ProductImage', label?: string | null, position?: number | null, disabled?: boolean | null, url?: string | null } | { __typename: 'ProductVideo', label?: string | null, position?: number | null, disabled?: boolean | null, video_content?: { media_type?: string | null, video_description?: string | null, video_metadata?: string | null, video_provider?: string | null, video_title?: string | null, video_url?: string | null } | null } | null> | null };

export type ProductPageGallery_ConfigurableProduct_Fragment = { url_key?: string | null, media_gallery?: Array<{ __typename: 'ProductImage', label?: string | null, position?: number | null, disabled?: boolean | null, url?: string | null } | { __typename: 'ProductVideo', label?: string | null, position?: number | null, disabled?: boolean | null, video_content?: { media_type?: string | null, video_description?: string | null, video_metadata?: string | null, video_provider?: string | null, video_title?: string | null, video_url?: string | null } | null } | null> | null };

export type ProductPageGallery_DownloadableProduct_Fragment = { url_key?: string | null, media_gallery?: Array<{ __typename: 'ProductImage', label?: string | null, position?: number | null, disabled?: boolean | null, url?: string | null } | { __typename: 'ProductVideo', label?: string | null, position?: number | null, disabled?: boolean | null, video_content?: { media_type?: string | null, video_description?: string | null, video_metadata?: string | null, video_provider?: string | null, video_title?: string | null, video_url?: string | null } | null } | null> | null };

export type ProductPageGallery_GroupedProduct_Fragment = { url_key?: string | null, media_gallery?: Array<{ __typename: 'ProductImage', label?: string | null, position?: number | null, disabled?: boolean | null, url?: string | null } | { __typename: 'ProductVideo', label?: string | null, position?: number | null, disabled?: boolean | null, video_content?: { media_type?: string | null, video_description?: string | null, video_metadata?: string | null, video_provider?: string | null, video_title?: string | null, video_url?: string | null } | null } | null> | null };

export type ProductPageGallery_SimpleProduct_Fragment = { url_key?: string | null, media_gallery?: Array<{ __typename: 'ProductImage', label?: string | null, position?: number | null, disabled?: boolean | null, url?: string | null } | { __typename: 'ProductVideo', label?: string | null, position?: number | null, disabled?: boolean | null, video_content?: { media_type?: string | null, video_description?: string | null, video_metadata?: string | null, video_provider?: string | null, video_title?: string | null, video_url?: string | null } | null } | null> | null };

export type ProductPageGallery_VirtualProduct_Fragment = { url_key?: string | null, media_gallery?: Array<{ __typename: 'ProductImage', label?: string | null, position?: number | null, disabled?: boolean | null, url?: string | null } | { __typename: 'ProductVideo', label?: string | null, position?: number | null, disabled?: boolean | null, video_content?: { media_type?: string | null, video_description?: string | null, video_metadata?: string | null, video_provider?: string | null, video_title?: string | null, video_url?: string | null } | null } | null> | null };

export type ProductPageGalleryFragment = ProductPageGallery_BundleProduct_Fragment | ProductPageGallery_ConfigurableProduct_Fragment | ProductPageGallery_DownloadableProduct_Fragment | ProductPageGallery_GroupedProduct_Fragment | ProductPageGallery_SimpleProduct_Fragment | ProductPageGallery_VirtualProduct_Fragment;
