/* hash:2035875163 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/magento-product/components/ProductPagePrice/ProductPagePriceTiers */

/** @see {@link file://./ProductPagePriceTiers.tsx} for source of original */
/** SOURCE_START */
import { PrivateQueryMask } from '@graphcommerce/graphql'
import { ProductPagePriceTiers as ProductPagePriceTiersConfigurableProductPagePriceTiers } from '@graphcommerce/magento-product-configurable/plugins/ConfigurableProductPage/ConfigurableProductPagePriceTiers'
import { Money } from '@graphcommerce/magento-store'
import { filterNonNullableKeys } from '@graphcommerce/next-ui'
import { Trans } from '@lingui/react'
import type { SxProps, Theme } from '@mui/material'
import type { DistributedOmit as OmitPrev } from 'type-fest'
import type { ProductPagePriceFragment } from './ProductPagePrice.gql'

export type ProductPagePriceTiersProps = {
  sx?: SxProps<Theme>
  product: ProductPagePriceFragment
}
export function ProductPagePriceTiersOriginal(props: ProductPagePriceTiersProps) {
  const { product, sx = [] } = props
  const priceTiers = filterNonNullableKeys(product?.price_tiers, [
    'quantity',
    'final_price',
    'discount',
  ])
  if (!priceTiers.length) return null
  return (
    <PrivateQueryMask sx={sx} variant='rectangular'>
      {priceTiers.map(({ quantity, final_price, discount }) => (
        <div key={quantity}>
          <Trans
            id='Buy {quantity} for <0/> and save {percent}%'
            components={{
              0: <Money {...final_price} />,
            }}
            values={{
              quantity,
              percent: discount.percent_off,
            }}
          />
        </div>
      ))}
    </PrivateQueryMask>
  )
}

/** SOURCE_END */

type ProductPagePriceTiersConfigurableProductPagePriceTiersProps = OmitPrev<
  React.ComponentProps<typeof ProductPagePriceTiersConfigurableProductPagePriceTiers>,
  'Prev'
>

const ProductPagePriceTiersConfigurableProductPagePriceTiersInterceptor = (
  props: ProductPagePriceTiersConfigurableProductPagePriceTiersProps,
) => (
  <ProductPagePriceTiersConfigurableProductPagePriceTiers
    {...props}
    Prev={ProductPagePriceTiersOriginal}
  />
)

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./ProductPagePriceTiers.tsx} for original source file
 * @see {ProductPagePriceTiersConfigurableProductPagePriceTiers} for source of applied plugin
 */
export const ProductPagePriceTiers =
  ProductPagePriceTiersConfigurableProductPagePriceTiersInterceptor
